use serde_json::Value;

use super::error_at_key;
use crate::config::ConfigDraftError;

pub(super) fn validate_numeric_ranges(value: &Value, raw: &str) -> Result<(), ConfigDraftError> {
    let checks = [
        (
            "fontSize",
            value.pointer("/overlay/appearance/fontSize"),
            16.0,
            72.0,
        ),
        (
            "fontWeight",
            value.pointer("/overlay/appearance/fontWeight"),
            400.0,
            800.0,
        ),
        (
            "secondaryFontWeight",
            value.pointer("/overlay/appearance/secondaryFontWeight"),
            400.0,
            800.0,
        ),
        (
            "lineHeight",
            value.pointer("/overlay/appearance/lineHeight"),
            0.8,
            2.0,
        ),
        (
            "autoApplyThreshold",
            value.pointer("/lyrics/providers/autoApplyThreshold"),
            0.0,
            100.0,
        ),
        (
            "autoApplyDurationToleranceSeconds",
            value.pointer("/lyrics/providers/autoApplyDurationToleranceSeconds"),
            0.0,
            60.0,
        ),
        (
            "autoSearchDebounceMs",
            value.pointer("/lyrics/providers/autoSearchDebounceMs"),
            0.0,
            5_000.0,
        ),
        (
            "capabilityPreferenceTolerance",
            value.pointer("/lyrics/providers/capabilityPreferenceTolerance"),
            0.0,
            20.0,
        ),
        (
            "title",
            value.pointer("/lyrics/providers/matchWeights/title"),
            0.0,
            100.0,
        ),
        (
            "artist",
            value.pointer("/lyrics/providers/matchWeights/artist"),
            0.0,
            100.0,
        ),
        (
            "album",
            value.pointer("/lyrics/providers/matchWeights/album"),
            0.0,
            100.0,
        ),
        (
            "duration",
            value.pointer("/lyrics/providers/matchWeights/duration"),
            0.0,
            100.0,
        ),
        (
            "fontSize",
            value.pointer("/lyrics/displays/statusBar/appearance/fontSize"),
            10.0,
            32.0,
        ),
        (
            "verticalOffset",
            value.pointer("/lyrics/displays/statusBar/appearance/verticalOffset"),
            -6.0,
            6.0,
        ),
        (
            "width",
            value.pointer("/lyrics/displays/statusBar/appearance/width"),
            120.0,
            360.0,
        ),
        (
            "maxWidth",
            value.pointer("/lyrics/displays/statusBar/appearance/maxWidth"),
            120.0,
            720.0,
        ),
        (
            "fontSize",
            value.pointer("/lyrics/displays/listWindow/appearance/fontSize"),
            12.0,
            56.0,
        ),
        (
            "backgroundOpacity",
            value.pointer("/lyrics/displays/listWindow/appearance/backgroundOpacity"),
            0.0,
            1.0,
        ),
        (
            "secondaryLineGap",
            value.pointer("/lyrics/displays/listWindow/appearance/secondaryLineGap"),
            0.0,
            32.0,
        ),
        (
            "activeOpacity",
            value.pointer("/lyrics/displays/listWindow/appearance/activeOpacity"),
            0.0,
            1.0,
        ),
        (
            "inactiveOpacity",
            value.pointer("/lyrics/displays/listWindow/appearance/inactiveOpacity"),
            0.0,
            1.0,
        ),
        (
            "fontSize",
            value.pointer("/lyrics/displays/notch/appearance/fontSize"),
            12.0,
            32.0,
        ),
        (
            "fontWeight",
            value.pointer("/lyrics/displays/notch/appearance/fontWeight"),
            400.0,
            800.0,
        ),
        (
            "secondaryFontWeight",
            value.pointer("/lyrics/displays/notch/appearance/secondaryFontWeight"),
            400.0,
            800.0,
        ),
        (
            "lineGap",
            value.pointer("/lyrics/displays/notch/appearance/lineGap"),
            0.0,
            32.0,
        ),
        (
            "maxWidth",
            value.pointer("/lyrics/displays/notch/appearance/maxWidth"),
            320.0,
            640.0,
        ),
        (
            "expandedMaxWidth",
            value.pointer("/lyrics/displays/notch/appearance/expandedMaxWidth"),
            440.0,
            640.0,
        ),
        (
            "topBorderRadius",
            value.pointer("/lyrics/displays/notch/appearance/topBorderRadius"),
            0.0,
            40.0,
        ),
        (
            "opacity",
            value.pointer("/overlay/appearance/opacity"),
            0.2,
            1.0,
        ),
        (
            "backgroundOpacity",
            value.pointer("/overlay/appearance/backgroundOpacity"),
            0.0,
            1.0,
        ),
        (
            "backgroundBlur",
            value.pointer("/overlay/appearance/backgroundBlur"),
            0.0,
            40.0,
        ),
        (
            "backgroundRadius",
            value.pointer("/overlay/appearance/backgroundRadius"),
            0.0,
            64.0,
        ),
        (
            "backgroundPaddingX",
            value.pointer("/overlay/appearance/backgroundPaddingX"),
            0.0,
            64.0,
        ),
        (
            "backgroundPaddingY",
            value.pointer("/overlay/appearance/backgroundPaddingY"),
            0.0,
            64.0,
        ),
        (
            "lineGap",
            value.pointer("/overlay/appearance/lineGap"),
            0.0,
            32.0,
        ),
        (
            "textShadowOffsetX",
            value.pointer("/overlay/appearance/textShadowOffsetX"),
            -20.0,
            20.0,
        ),
        (
            "textShadowOffsetY",
            value.pointer("/overlay/appearance/textShadowOffsetY"),
            -20.0,
            20.0,
        ),
        (
            "textShadowBlur",
            value.pointer("/overlay/appearance/textShadowBlur"),
            0.0,
            40.0,
        ),
        (
            "textStrokeWidth",
            value.pointer("/overlay/appearance/textStrokeWidth"),
            0.0,
            8.0,
        ),
        (
            "secondaryFontScale",
            value.pointer("/overlay/appearance/secondaryFontScale"),
            0.35,
            1.0,
        ),
        (
            "translationFontScale",
            value.pointer("/overlay/appearance/translationFontScale"),
            0.35,
            1.0,
        ),
        (
            "romanizationFontScale",
            value.pointer("/overlay/appearance/romanizationFontScale"),
            0.35,
            1.0,
        ),
    ];
    for (key, candidate, minimum, maximum) in checks {
        if let Some(candidate) = candidate {
            let number = candidate
                .as_f64()
                .ok_or_else(|| error_at_key(raw, key, &format!("{key} 必须是数字")))?;
            if !number.is_finite() || number < minimum || number > maximum {
                return Err(error_at_key(
                    raw,
                    key,
                    &format!("{key} 必须在 {minimum}–{maximum} 之间"),
                ));
            }
        }
    }
    if let Some(candidate) = value.pointer("/lyrics/providers/autoSearchDebounceMs") {
        if let Some(milliseconds) = candidate.as_u64() {
            if milliseconds % 100 != 0 {
                return Err(error_at_key(
                    raw,
                    "autoSearchDebounceMs",
                    "autoSearchDebounceMs 必须是 100 毫秒的整数倍",
                ));
            }
        }
    }
    Ok(())
}
