export const libraryManagerEn = {
  title: "Library", description: "Manage the songs, lyrics, and artists already known to Lyrics Plus.", tabsLabel: "Library categories",
  tabs: { songs: "Songs", lyrics: "Lyrics", artists: "Artists" },
  search: "Search library", searchPlaceholder: "Search by title, artist, album, alias, or source", loading: "Loading…", preview: "Quick preview", openDetail: "Open full details", back: "Back", none: "None",
  previousPage: "Previous page", nextPage: "Next page", pageSummary: "Page {{page}} of {{totalPages}} · {{total}} items",
  paginationLabel: "Library pagination", itemsPerPage: "Items per page", pageSizeOption: "{{count}} / page", goToPage: "Go to page {{page}}",
  song: "Song", lyric: "Lyrics", artist: "Artist", album: "Album", duration: "Duration", version: "Version", platforms: "Platforms", lyricsCount: "Lyrics", songCount: "Songs", size: "Size", format: "Format", capabilities: "Capabilities", sources: "Sources", bindings: "Bindings", statusLabel: "Status", actions: "Actions", details: "Details",
  emptySongs: "No known songs", emptyLyrics: "No lyrics match these filters", emptyArtists: "No known artists", selectSong: "Select a song to preview it", selectLyric: "Select lyrics to preview them", selectArtist: "Select an artist to preview them", selectAll: "Select all visible lyrics",
  defaultLyric: "Default lyrics", candidateLyric: "Candidate", unavailable: "Unavailable", externalIds: "External IDs", fingerprint: "Content fingerprint", rawCredit: "Original credit", rawCredits: "Original credits", aliases: "Aliases", canonicalName: "Canonical name",
  artistIdentity: "Artist identity", manageArtist: "Manage artist", platformTracks: "Source observations", songSources: "Sources", systemSource: "System · {{app}}", unknownSourceApp: "Unknown app", lyricResources: "Lyrics resources", physicalSources: "Physical sources", relatedSongs: "Related songs", boundSongs: "Bound songs", openSong: "Open song", noBoundSongs: "Not bound to a song", noBoundLyrics: "No lyrics bound",
  bindLyric: "Bind lyrics", bindSong: "Bind to song", bind: "Bind", bound: "Lyrics bound", bindRule: "If the song has no default lyrics, these become the default. Otherwise they are added as a candidate unless replacement is selected.", replaceDefault: "Replace the current default lyrics", setDefault: "Set as default", defaultChanged: "Default lyrics changed",
  unbind: "Unbind", unbound: "Lyrics unbound", unbindTitle: "Unbind these lyrics?", unbindDescription: "This removes the song-to-lyrics relationship and any matching platform override. No file will be deleted and no candidate will be promoted.",
  detach: "Split out", detached: "Platform track split out", detachTitle: "Split this platform track?", detachDescription: "This platform observation becomes a separate song and will not inherit lyrics.", associate: "Associate", associated: "Songs associated", associateTitle: "Associate these songs?", associateDescription: "The candidate platform observations will move into this recording.",
  status: { all: "All statuses", inUse: "In use", candidate: "Candidate only", unbound: "Unbound" }, source: { all: "All sources", managed: "Managed", cache: "Cache", local: "External local", legacy: "Read-only history" },
  similarLyrics: "Similar lyrics", similarTitle: "Similar lyrics queue", similarDescription: "Text is analyzed automatically; you decide whether to merge or keep each group separate.", analyzing: "Analyzing lyric text…", noSimilar: "No unresolved similar lyrics", highSimilarity: "Highly similar", similar: "Similar", recommended: "Recommended", durationConflict: "Duration conflict", versionConflict: "Version conflict", notDuplicate: "Keep separate", merge: "Merge", merged: "Lyrics merged", mergeTitle: "Merge this group?", mergeDescription: "Bindings, platform overrides, and offsets move to the selected lyrics. Files are not deleted automatically.", previewUnavailable: "No readable preview",
  similarSongs: "Similar songs", similarSongsTitle: "Similar songs queue", similarSongsDescription: "Review possible duplicate songs one pair at a time, then merge them or keep them separate.", analyzingSimilarSongs: "Analyzing similar songs…", noSimilarSongs: "No unresolved similar songs", similarSongsScore: "Match score {{value}}%", similarSongKinds: { originalRelation: "Original relation", sharedIdentifier: "Shared identifier", metadata: "Metadata match" }, mergeBlocked: "Resolve platform conflict first", selectKeeper: "Select the song to keep", keepSong: "Keep {{title}}", songResourceSummary: "{{sources}} sources · {{lyrics}} lyrics", openSongNamed: "Open {{title}}", notSameSong: "Not the same song", similarSongsKeptSeparate: "The songs will remain separate", mergeSongs: "Merge songs", similarSongsMerged: "Songs merged", mergeSimilarSongsTitle: "Merge these songs?", mergeSimilarSongsDescription: "Keep “{{keeper}}” and move the source observations, lyrics bindings, platform overrides, and external IDs from “{{redundant}}” into it.",
  cleanup: "Clean unbound", cleanupTitle: "Clean unbound lyrics", cleanupDescription: "{{count}} writable managed/cache files use {{size}}. External and read-only files are excluded.", confirmCleanup: "Delete selected files", cleanupDone: "Deleted {{count}} files and released {{size}}", sourceDeleted: "Lyrics source deleted", deleteSourceTitle: "Delete this physical source?", deleteSourceDescription: "Only this writable file and its index entry are removed. At least one readable source must remain.", requiredSource: "Only readable source", readOnly: "Read-only", memorySource: "No physical path", lyricPreview: "Lyrics preview", formattedLyrics: "Formatted lyrics", rawLyrics: "Raw lyrics",
  artistSummary: "{{songs}} songs · {{aliases}} aliases", artistNameSaved: "Artist name saved", aliasPlaceholder: "Add an alias", addAlias: "Add alias", aliasAdded: "Alias added", aliasRemoved: "Alias removed", removeAlias: "Remove alias {{alias}}",
};

export const libraryManagerZhCN = {
  ...libraryManagerEn,
  title: "资料库", description: "集中管理 Lyrics Plus 已知的歌曲、歌词与歌手。", tabsLabel: "资料库分类", tabs: { songs: "歌曲", lyrics: "歌词", artists: "歌手" },
  search: "搜索资料库", searchPlaceholder: "搜索歌名、歌手、专辑、别名或来源", loading: "正在载入…", preview: "快速预览", openDetail: "打开完整详情", back: "返回", none: "无", previousPage: "上一页", nextPage: "下一页", pageSummary: "第 {{page}} / {{totalPages}} 页 · 共 {{total}} 项",
  paginationLabel: "资料库分页", itemsPerPage: "每页条数", pageSizeOption: "每页 {{count}} 条", goToPage: "前往第 {{page}} 页",
  song: "歌曲", lyric: "歌词", artist: "歌手", album: "专辑", duration: "时长", version: "版本", platforms: "平台", lyricsCount: "歌词", songCount: "歌曲数", size: "大小", format: "格式", capabilities: "能力", sources: "来源", bindings: "绑定", statusLabel: "状态", actions: "操作", details: "详情",
  emptySongs: "暂无应用已知歌曲", emptyLyrics: "没有符合筛选条件的歌词", emptyArtists: "暂无应用已知歌手", selectSong: "选择歌曲查看速览", selectLyric: "选择歌词查看速览", selectArtist: "选择歌手查看速览", selectAll: "选择本页全部歌词",
  defaultLyric: "默认歌词", candidateLyric: "候选歌词", unavailable: "不可用", externalIds: "外部标识", fingerprint: "内容指纹", rawCredit: "平台原始署名", rawCredits: "平台原始署名", aliases: "别名", canonicalName: "规范名称", artistIdentity: "歌手身份", manageArtist: "管理歌手", platformTracks: "来源观察", songSources: "来源", systemSource: "系统 · {{app}}", unknownSourceApp: "未知应用", lyricResources: "歌词资源", physicalSources: "物理来源", relatedSongs: "关联歌曲", boundSongs: "已绑定歌曲", openSong: "打开歌曲", noBoundSongs: "尚未绑定歌曲", noBoundLyrics: "尚未绑定歌词",
  bindLyric: "绑定歌词", bindSong: "绑定到歌曲", bind: "绑定", bound: "歌词已绑定", bindRule: "歌曲没有默认歌词时直接设为默认；已有默认歌词时先作为候选，除非明确选择替换。", replaceDefault: "替换当前默认歌词", setDefault: "设为默认", defaultChanged: "默认歌词已更新", unbind: "解绑", unbound: "已解除歌词绑定", unbindTitle: "解除这份歌词的绑定？", unbindDescription: "会删除歌曲与歌词的关系及对应平台覆盖；不会删除文件，也不会自动提升其他候选。",
  detach: "拆分", detached: "平台曲目已拆分", detachTitle: "拆分这条平台曲目？", detachDescription: "该平台观察会成为独立歌曲，且暂不绑定歌词。", associate: "合并关联", associated: "歌曲已关联", associateTitle: "合并关联这两首歌曲？", associateDescription: "候选歌曲的平台观察会迁移到当前录音。",
  status: { all: "全部状态", inUse: "使用中", candidate: "仅候选", unbound: "未绑定" }, source: { all: "全部来源", managed: "应用托管", cache: "缓存", local: "外部本地", legacy: "只读历史" },
  similarLyrics: "相似歌词", similarTitle: "相似歌词队列", similarDescription: "系统自动分析正文，由你决定合并或保持分开。", analyzing: "正在分析歌词正文…", noSimilar: "没有待处理的相似歌词", highSimilarity: "高度相似", similar: "相似", recommended: "推荐保留", durationConflict: "时长冲突", versionConflict: "版本冲突", notDuplicate: "不是重复，保持分开", merge: "合并", merged: "歌词已合并", mergeTitle: "合并这一组歌词？", mergeDescription: "绑定、平台覆盖和偏移会迁移到所选歌词；物理文件不会自动删除。", previewUnavailable: "没有可读取的预览",
  similarSongs: "相似歌曲", similarSongsTitle: "相似歌曲队列", similarSongsDescription: "逐对审核可能重复的歌曲，并决定合并或保持分开。", analyzingSimilarSongs: "正在分析相似歌曲…", noSimilarSongs: "没有待处理的相似歌曲", similarSongsScore: "匹配度 {{value}}%", similarSongKinds: { originalRelation: "原关联歌曲", sharedIdentifier: "共享标识", metadata: "元数据匹配" }, mergeBlocked: "请先处理平台冲突", selectKeeper: "选择要保留的歌曲", keepSong: "保留 {{title}}", songResourceSummary: "{{sources}} 个来源 · {{lyrics}} 份歌词", openSongNamed: "打开 {{title}}", notSameSong: "不是同一首，保持分开", similarSongsKeptSeparate: "已将两首歌曲保持分开", mergeSongs: "合并歌曲", similarSongsMerged: "歌曲已合并", mergeSimilarSongsTitle: "合并这两首歌曲？", mergeSimilarSongsDescription: "保留“{{keeper}}”，并将“{{redundant}}”的来源观察、歌词绑定、平台覆盖和外部标识迁入其中。",
  cleanup: "清理未绑定", cleanupTitle: "清理未绑定歌词", cleanupDescription: "共有 {{count}} 个可写托管/缓存文件，占用 {{size}}。外部和只读文件已排除。", confirmCleanup: "删除所选文件", cleanupDone: "已删除 {{count}} 个文件，释放 {{size}}", sourceDeleted: "歌词来源已删除", deleteSourceTitle: "删除这个物理来源？", deleteSourceDescription: "只删除这个可写文件及索引，并且至少保留一个可读来源。", requiredSource: "唯一可用来源", readOnly: "只读", memorySource: "无物理路径", lyricPreview: "歌词预览", formattedLyrics: "格式化歌词", rawLyrics: "原歌词",
  artistSummary: "{{songs}} 首歌曲 · {{aliases}} 个别名", artistNameSaved: "歌手名称已保存", aliasPlaceholder: "添加一个别名", addAlias: "添加别名", aliasAdded: "别名已添加", aliasRemoved: "别名已移除", removeAlias: "移除别名 {{alias}}",
};

export const libraryManagerZhTW = {
  ...libraryManagerZhCN,
  paginationLabel: "資料庫分頁", itemsPerPage: "每頁筆數", pageSizeOption: "每頁 {{count}} 筆", goToPage: "前往第 {{page}} 頁",
  description: "集中管理 Lyrics Plus 已知的歌曲、歌詞與歌手。", tabsLabel: "資料庫分類", tabs: { songs: "歌曲", lyrics: "歌詞", artists: "歌手" }, searchPlaceholder: "搜尋歌名、歌手、專輯、別名或來源", loading: "正在載入…", openDetail: "開啟完整詳情", back: "返回", pageSummary: "第 {{page}} / {{totalPages}} 頁 · 共 {{total}} 項", lyric: "歌詞", album: "專輯", lyricsCount: "歌詞", statusLabel: "狀態", details: "詳情", defaultLyric: "預設歌詞", candidateLyric: "候選歌詞", unavailable: "無法使用", platformTracks: "來源觀察", songSources: "來源", systemSource: "系統 · {{app}}", unknownSourceApp: "未知應用程式", bindLyric: "綁定歌詞", bindSong: "綁定到歌曲", bind: "綁定", unbind: "解除綁定", source: { all: "全部來源", managed: "應用程式管理", cache: "快取", local: "外部本機", legacy: "唯讀歷史" }, status: { all: "全部狀態", inUse: "使用中", candidate: "僅候選", unbound: "未綁定" }, similarLyrics: "相似歌詞", cleanup: "清理未綁定", readOnly: "唯讀", lyricPreview: "歌詞預覽", formattedLyrics: "格式化歌詞", rawLyrics: "原始歌詞",
  similarSongs: "相似歌曲", similarSongsTitle: "相似歌曲佇列", similarSongsDescription: "逐對審核可能重複的歌曲，並決定合併或保持分開。", analyzingSimilarSongs: "正在分析相似歌曲…", noSimilarSongs: "沒有待處理的相似歌曲", similarSongsScore: "匹配度 {{value}}%", similarSongKinds: { originalRelation: "原關聯歌曲", sharedIdentifier: "共用識別碼", metadata: "中繼資料匹配" }, mergeBlocked: "請先處理平台衝突", selectKeeper: "選擇要保留的歌曲", keepSong: "保留 {{title}}", songResourceSummary: "{{sources}} 個來源 · {{lyrics}} 份歌詞", openSongNamed: "開啟 {{title}}", notSameSong: "不是同一首，保持分開", similarSongsKeptSeparate: "已將兩首歌曲保持分開", mergeSongs: "合併歌曲", similarSongsMerged: "歌曲已合併", mergeSimilarSongsTitle: "合併這兩首歌曲？", mergeSimilarSongsDescription: "保留「{{keeper}}」，並將「{{redundant}}」的來源觀察、歌詞綁定、平台覆蓋和外部識別碼遷入其中。",
};

export const libraryManagerJa = {
  ...libraryManagerEn,
  title: "ライブラリ", description: "Lyrics Plus が認識した曲、歌詞、アーティストを管理します。", tabsLabel: "ライブラリ分類", tabs: { songs: "曲", lyrics: "歌詞", artists: "アーティスト" }, search: "ライブラリを検索", searchPlaceholder: "曲名、アーティスト、アルバム、別名、ソースを検索", loading: "読み込み中…", preview: "クイックプレビュー", openDetail: "詳細を開く", back: "戻る", none: "なし", song: "曲", lyric: "歌詞", artist: "アーティスト", album: "アルバム", duration: "時間", platforms: "プラットフォーム", lyricsCount: "歌詞", songCount: "曲数", size: "サイズ", format: "形式", capabilities: "機能", sources: "ソース", bindings: "関連付け", statusLabel: "状態", actions: "操作", details: "詳細", emptySongs: "認識済みの曲はありません", emptyLyrics: "条件に合う歌詞はありません", emptyArtists: "認識済みのアーティストはいません", defaultLyric: "既定の歌詞", candidateLyric: "候補", unavailable: "利用不可", aliases: "別名", canonicalName: "正式名", manageArtist: "アーティストを管理", platformTracks: "ソースの観測", songSources: "ソース", systemSource: "システム · {{app}}", unknownSourceApp: "不明なアプリ", relatedSongs: "関連曲", boundSongs: "関連付け済みの曲", bindLyric: "歌詞を関連付け", bindSong: "曲に関連付け", bind: "関連付け", unbind: "解除", status: { all: "すべて", inUse: "使用中", candidate: "候補のみ", unbound: "未関連付け" }, source: { all: "すべてのソース", managed: "管理対象", cache: "キャッシュ", local: "外部ローカル", legacy: "読み取り専用履歴" }, similarLyrics: "類似歌詞", similarTitle: "類似歌詞キュー", analyzing: "歌詞を分析中…", noSimilar: "未処理の類似歌詞はありません", notDuplicate: "別々に保持", merge: "統合", cleanup: "未関連付けを整理", readOnly: "読み取り専用", lyricPreview: "歌詞プレビュー", formattedLyrics: "整形済み歌詞", rawLyrics: "原文歌詞", addAlias: "別名を追加",
  similarSongs: "類似曲", similarSongsTitle: "類似曲キュー", similarSongsDescription: "重複している可能性のある曲を2曲ずつ確認し、統合するか別々に保持します。", analyzingSimilarSongs: "類似曲を分析中…", noSimilarSongs: "未処理の類似曲はありません", similarSongsScore: "一致度 {{value}}%", similarSongKinds: { originalRelation: "元の関連曲", sharedIdentifier: "共通識別子", metadata: "メタデータ一致" }, mergeBlocked: "先にプラットフォームの競合を解消してください", selectKeeper: "保持する曲を選択", keepSong: "{{title}}を保持", songResourceSummary: "{{sources}}ソース · 歌詞{{lyrics}}件", openSongNamed: "{{title}}を開く", notSameSong: "別の曲として保持", similarSongsKeptSeparate: "2曲を別々に保持します", mergeSongs: "曲を統合", similarSongsMerged: "曲を統合しました", mergeSimilarSongsTitle: "この2曲を統合しますか？", mergeSimilarSongsDescription: "「{{keeper}}」を保持し、「{{redundant}}」のソース観測、歌詞の関連付け、プラットフォーム設定、外部IDを移行します。",
};

export const libraryManagerKo = {
  ...libraryManagerEn,
  title: "라이브러리", description: "Lyrics Plus가 알고 있는 노래, 가사, 아티스트를 관리합니다.", tabsLabel: "라이브러리 분류", tabs: { songs: "노래", lyrics: "가사", artists: "아티스트" }, search: "라이브러리 검색", searchPlaceholder: "제목, 아티스트, 앨범, 별칭 또는 소스 검색", loading: "불러오는 중…", preview: "빠른 미리보기", openDetail: "전체 세부 정보 열기", back: "뒤로", none: "없음", song: "노래", lyric: "가사", artist: "아티스트", album: "앨범", duration: "길이", platforms: "플랫폼", lyricsCount: "가사", songCount: "노래 수", size: "크기", format: "형식", capabilities: "기능", sources: "소스", bindings: "연결", statusLabel: "상태", actions: "작업", details: "상세", emptySongs: "알려진 노래가 없습니다", emptyLyrics: "필터와 일치하는 가사가 없습니다", emptyArtists: "알려진 아티스트가 없습니다", defaultLyric: "기본 가사", candidateLyric: "후보", unavailable: "사용 불가", aliases: "별칭", canonicalName: "표준 이름", manageArtist: "아티스트 관리", platformTracks: "소스 관측", songSources: "소스", systemSource: "시스템 · {{app}}", unknownSourceApp: "알 수 없는 앱", relatedSongs: "연결된 노래", boundSongs: "연결된 노래", bindLyric: "가사 연결", bindSong: "노래에 연결", bind: "연결", unbind: "연결 해제", status: { all: "모든 상태", inUse: "사용 중", candidate: "후보만", unbound: "연결 안 됨" }, source: { all: "모든 소스", managed: "앱 관리", cache: "캐시", local: "외부 로컬", legacy: "읽기 전용 기록" }, similarLyrics: "유사 가사", similarTitle: "유사 가사 대기열", analyzing: "가사 분석 중…", noSimilar: "처리할 유사 가사가 없습니다", notDuplicate: "별도로 유지", merge: "병합", cleanup: "미연결 가사 정리", readOnly: "읽기 전용", lyricPreview: "가사 미리보기", formattedLyrics: "서식 있는 가사", rawLyrics: "원본 가사", addAlias: "별칭 추가",
  similarSongs: "유사 노래", similarSongsTitle: "유사 노래 대기열", similarSongsDescription: "중복 가능성이 있는 노래를 두 곡씩 검토하고 병합하거나 따로 유지합니다.", analyzingSimilarSongs: "유사 노래 분석 중…", noSimilarSongs: "처리할 유사 노래가 없습니다", similarSongsScore: "일치도 {{value}}%", similarSongKinds: { originalRelation: "원래 연결된 노래", sharedIdentifier: "공유 식별자", metadata: "메타데이터 일치" }, mergeBlocked: "먼저 플랫폼 충돌을 해결하세요", selectKeeper: "유지할 노래 선택", keepSong: "{{title}} 유지", songResourceSummary: "소스 {{sources}}개 · 가사 {{lyrics}}개", openSongNamed: "{{title}} 열기", notSameSong: "다른 노래로 유지", similarSongsKeptSeparate: "두 노래를 따로 유지합니다", mergeSongs: "노래 병합", similarSongsMerged: "노래를 병합했습니다", mergeSimilarSongsTitle: "두 노래를 병합할까요?", mergeSimilarSongsDescription: "‘{{keeper}}’를 유지하고 ‘{{redundant}}’의 소스 관측, 가사 연결, 플랫폼 설정 및 외부 ID를 이동합니다.",
};
